#%RAML 1.0
title: ACME Banking API
description: |-
  Base URI = URL final donde estara la app, mycompany.com/api.

  This API offers access to personal banking data, around customers, transactions and accounts.
mediaType:
  - application/json
version: v1
protocols:
  - HTTPS
  - HTTP
/accounts:
  get:
    displayName: Get All Accounts Info
/customers:
  get:
    displayName: Get All Customers Info
/transactions:
  get:
    displayName: Get All Transactions
