#%RAML 1.0
title: ACME Banking API
description: |-
  This API offers access to personal banking data, around customers, transactions and accounts.
mediaType:
  - application/json
version: v1
protocols:
  - HTTPS
  - HTTP


/accounts:
  post:
    displayName: Create a new account

/accounts/{account_id}:

/customers:
  get:
    displayName: Get all customers in the bank
  post:
    displayName: Create a new customer
  
  /{customer_id}:
    get:
      displayName: Get information for a specific customer
    patch:
      displayName: Update information for a specific customer
    delete:
      displayName: Delete information for a specific customer

/customers/{customer_id}/accounts:
  get:
    displayName: Get all accounts for a specific customer
    

/transactions:
  get:
    displayName: Get All Transactions
