#%RAML 1.0
title: ACME Banking API
description: |-
  This API offers access to personal banking data, around customers, transactions and accounts.
mediaType:
  - application/json
version: v1
protocols:
  - HTTPS
  - HTTP


/accounts:
  get:
    displayName: Get All Accounts Info

/customers:
  get:
    displayName: Get all customers in the bank
  post:
    displayName: Create a new customer
  
  /{customer_id}:
    get:


/transactions:
  get:
    displayName: Get All Transactions
