#%RAML 1.0 NamedExample
value:
  customerID: 8f19cb50-3f57-4d38
  firstName: Sarah
  lastName: Connor
  displayName: S Connor
  address: 
    addressLine1: Fake Street 99
    addressLine2: Apt.#620
    city: Amsterdam
    state: Noorth-Holland
    zipCode: '94108'
    country: Netherlands
  phone: 415-000-0000
  email: sarah@example.com
  ssn: 444-45-3657
  dateOfBirth: 1999-01-01
