#%RAML 1.0 DocumentationItem
title: Getting Started with ACME Bank API
# if we use pipe | , then we can use markdown directly
content: |
  **ACME BANK** API offers access to _customers_, _accounts_ and _transactions_ data.



  ---

  > Note: This API is under development!
  
  So we offer these resources:
    - Customers
    - Accounts
    - Transactions


  | Resource | Description |
  | ------ | ----------- |
  | Accounts   | path to data files to supply the data that will be passed into templates. |
  | Customers | engine to be used for processing templates. Handlebars is the default. |
  | Transactions    | extension to be used for dest files. |

  ```
  Example request:
    curl GET https://fake-acme.com/api/users
  ```
  
  