#%RAML 1.0 DocumentationItem
title: Getting Started with ACME Bank API
# if we use pipe | , then we can use markdown directly
content: |
  **ACME BANK** API offers access to _customers_, _accounts_ and _transactions_ data.

  So we offer these resources:
    - Customers
    - Accounts
    - Transactions

  